### ISSUE TITLE
Ensure geoserver_mnt folders are created if not existing

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/sauber-sdi-docker#105]
Since the `geoserver_mnt` is no more under version control (see #100) I am discovering the following when starting the stack on a cleaned setup:

GeoServer service does not start anymore saying `invalid mount config for type "bind": bind source path does not exist` . In case I manually create  `geoserver_mnt/geoserver_data` and `geoserver_mnt/raster_data` GeoServer starts up well.

Due to https://github.com/docker/compose/issues/2781 our shorthand syntax `./geoserver_mnt/geoserver_data:/opt/geoserver_data/:Z` should create the mount folders if not existing, but they are not as described above. I am pretty sure this was the case in the past. Maybe something changed here?

Maybe having a script creating the folders `geoserver_mnt/geoserver_data` and `geoserver_mnt/raster_data` if not existing might be an option.

**Comment by JakobMiksch** [comment]
Maybe autocreation of directories only works with `docker-compose` but with `docker stack`.
