### ISSUE TITLE
GeoServer not reachable 

### ISSUE THREAD

**Issue by jdk24** [meggsimum/sauber-sdi-docker#124]
Under some circumstances, the GeoServer instance appears unavailable after stack deployment. 
Using this issue to try and identify the issue / whether it is one.

**Comment by JakobMiksch** [comment]
I had the same problem, I think I fixed it by removing the directories `raster_data` and `geoserver_data`. I suspect it might have something to do with the permissions of the directories. But the next time when it happens I will try to collect more logs

**Comment by chrismayer** [comment]
Thanks you. Please re-open if this happens again or if we get to know more about this.
