### ISSUE TITLE
GS init cannot connect to database

### ISSUE THREAD

**Issue by jdk24** [meggsimum/sauber-sdi-docker#133]
GS init showed as complete but did not create initial layers. First time this issue occured. 

Root causes from log: 

```
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The connection attempt failed.)
org.postgresql.util.PSQLException: The connection attempt failed.
java.net.UnknownHostException: db
```
Complete [gs_init_log.txt](https://github.com/meggsimum/sauber-sdi-docker/files/6944621/gs_init_log.txt) 

Worked like a charm on restarting service manually.
Maybe GS init tries to connect to DB after the container exists but the DB itself is still starting. This is one of the shortcomings of `depends-on:` in compose file. 

If this comes up again, we could implement something like wait_for_it.sh. 
[Docker best practices.](https://github.com/vishnubob/wait-for-it#wait-for-it)
[Source.](https://docs.docker.com/compose/startup-order/)  

For now just for documentation.

**Comment by JakobMiksch** [comment]
alright, so you mean we should both wait for `geoserver` and `db` to be up and running?

**Comment by jdk24** [comment]
It looks to my untrained eye like an issue between GS -> DB, because GS_init's cron happened to run exactly during DB startup.

Quick and dirty would be just delaying the script execution with `sleep 60` or the like 
I'm only aware of `wait_for_it.sh`, perhaps there's easier methods for us. e.g. quering `db:3000/raster_metadata`. PostgREST gives `{"message":"Database connection lost, retrying the connection."}` if the DB isn't available...
