### ISSUE TITLE
Make sure workspace "simulation" exists

### ISSUE THREAD

**Issue by jdk24** [meggsimum/sauber-sdi-docker#161]
Need to check if done by REST API call or needed to be added to `geoserver_init`

**Comment by JakobMiksch** [comment]
we could add the workspace `simulation` to this line https://github.com/meggsimum/sauber-sdi-docker/blob/master/geoserver_init/010_init-gs.js#L16
then it would be automatically created if it does not exist
would that solve the problem ?
