### ISSUE TITLE
New FeatureType (layer) for demonstration purposes

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/sauber-sdi-docker#70]
we need a new FeatureType(layer) for demonstration purposes. It should be similar to `fv_wfs`  which currently has these properties (with example values):

```
gml_id (String) = fv_wfs.166                
component_id (Integer) = 7                  
component_name (String) = PM10_GM1H24H      
station_id (Integer) = 13567                
station_code (String) = NETT                
max_datetime (String) = 2021-04-02T23:00:00Z
min_datetime (String) = 2021-02-21T00:00:00Z
series (String) = [{"datetime" : "2021-04-02
```

for LANUV stations it is possible to generate URLs to a photo of the station and its website using the `station_code` property. In case of `BOTT`: 
- website: `https://www.lanuv.nrw.de/luqs/messorte/steckbrief.php?ort=BOTT`
- image: `https://www.lanuv.nrw.de/luqs/messorte/bilder/BOTT.jpg`

for LUBW stations our `stations_code` does not seem to fit their official URLs. For example "Bad Cannstadt"
- our code is `S-BC`
- its website is `https://www.lubw.baden-wuerttemberg.de/luft/messwerte-immissionswerte?comp=O3&id=DEBW013#diagramm`
- and the respective code/id seems to be `DEBW013`

Unfortunately the photos of the LUBW  stations seem to be hidden in a [PDF](https://www.lubw.baden-wuerttemberg.de/documents/10184/705223/DEBW013_S-BC.pdf)

###  possible additional properties (compared to `fv_wfs`)

- [ ] pre-computed properties for `image_url` and/or `station_url` 
- [ ] human-readable `description`
- [ ] links to other ressources e.g. a diagram or dashboard
- [ ] consider removing the `series` property, because it makes the size of the features very big. Alternatively the layer could come  in two version. One with, and one without `series` property

**Comment by jdk24** [comment]
Thank you for the listing! 
First, just to clarify, this would leave:

component_id,
component_name,
station_id,
station_code, 
max_datetime, 
min_datetime,
profile_url,
image_url,
description,
external_resources_x(link to diagram),
external_resources_y(link to dashboard),
external_resources_z(.... can be added later),

and probably the station name

Anything we should add or omit on this list?

Feel free to edit this (if allowed).


Secondly, the Stuttgart stations DO technically have [profiles](https://www.stadtklima-stuttgart.de/index.php?luft_messdaten_station_str ) but without any useful reference in the URL. Hardcode?

**Comment by JakobMiksch** [comment]
@jdk24 

We could also add the German and/or English name of the pollutant, e.g. 'Ozon, Stickstoffdioxid, Stickstoffmonoxid, Feinstaub' this might be easier to understand for non-technical people. 

```
- component_id,
- component_name,
- component_name_german <--
- component_name_english  <--
- station_id,
- station_code,
- max_datetime,
- min_datetime,
- profile_url,
- image_url,
- description,
- external_resources_x (link to diagram),
- external_resources_y (link to dashboard),
- external_resources_z (.... can be added later),
```

- regarding Stuttgart: as I see there are only 4 stations in Stuttgart. Hence, hardcoding sounds doable, right?

**Comment by jdk24** [comment]
@JakobMiksch It's all doable. 
I'll create an "auxiliary-" table to hold the extra information, then aggregate everything in a view. 
Will be added to the incremental DB updates.

**Comment by chrismayer** [comment]
+1 for the list of attributes above.

Just thinking loud: Would it be useful (at first place) and doable at all (at second place) to have some little aggregated station measurement values? For example values of the last 2 hours with a period of mins. Maybe in oder to show a little diagram as trend. Surely not intended to be a full fledged chart, since this is provided by SAG dashboard (which will be linked).

**Comment by jdk24** [comment]
This would be fv_wfs only with a filter on the "series" column. 

The resulting view would probably best look like


| stat_name  | code | more_stat_metainfo(url) | component | comp_name  | more... | last_x_hours                        |
|------------|------|-------------------------|-----------|------------|---------|-------------------------------------|
| heidelberg | hd   | ...                     | no2       | stickstoff | ...     | [{"datetime":1234567,"val":10,...}] |
| heidelberg | hd   | ...                     | pm10      | feinstaub  | ...     | [{"datetime":1234567,"val":20,...}] |
| mannheim   | ma   | ...                     | no2       | stickstoff | ...     | ...                                 |


So very doable if desired.

**Comment by JakobMiksch** [comment]
I like @chrismayer 's idea. @jdk24 this prototype table looks fine.

**Comment by jdk24** [comment]
Have a look at  `station_data.fv_station_metadata` for your consideration.

**Comment by chrismayer** [comment]
This is done, IMHO. What do you think @JakobMiksch and @jdk24 ? Please close if you agree

**Comment by JakobMiksch** [comment]
yes, the featuretype in the production system is available and works well. 
If the code for the creation is already merge, this issue can be closed from my side.

**Comment by jdk24** [comment]
Merged in https://github.com/meggsimum/sauber-sdi-docker/pull/64/files#diff-67993b717b155fcf4ecbd158b06a7d4a20efeb45d24fd84b4149f1f364b2cea3R16-R23 ff. so can be closed imo.

**Comment by JakobMiksch** [comment]
@jdk24 great, then it can be closed from my side

**Comment by chrismayer** [comment]
Done. FeatureType used in here: https://sauber-projekt.meggsimum.de/station-viewer/
